### ISSUE TITLE
Always Show Tab Bar injects a tabs container prior to tree-view panel.

### ISSUE THREAD

**Issue by jasesmith** [jasesmith/newton-dark-ui#4]
![newton-ui_tab-bar-issue](https://cloud.githubusercontent.com/assets/1619521/26270291/0bf537f4-3cb7-11e7-9364-dca7349dc971.png)

**Comment by pleaseremove** [comment]
I am also seeing this issue

**Comment by sumdog** [comment]
Can confirm issue on atom 1.18

**Comment by pleaseremove** [comment]
I am still seeing the issue on 1.18.0

**Comment by jasesmith** [comment]
Just published version 1.1.8 that should fix this issue with the newton-dark-ui theme.

**Comment by pleaseremove** [comment]
Hi

Thanks for doing this, however not seeing any updates on the repo. Last commit 7 months ago, no new release tags and atom auto update and plugin site agree. 

Thanks

Craig

**Comment by jasesmith** [comment]
I just noticed the fix didn't work as well. Looking into solving again.

**Comment by jasesmith** [comment]
Fixed again, hopefully for real this time. I inadvertently applied the fix to the newton-dark-syntax theme and not the -ui theme. Oops! Update 1.1.3 should _solve*_ this odd layout issue. 

* I'm not entirely sure what that "Projects" tab-bar is used for so my fix may render other packages that use that tab-bar unusable as I'm forcing `display: none` on that container.
